document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'ie=edge\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'../bootstrap/bootstrap-3.3.7-dist/css/bootstrap.min.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/main.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/footer.css\'>");
document.writeln("    <title>Document</title>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("");
document.writeln("        <div class=\'footer\'>");
document.writeln("                <div class=\'footer-center\'>");
document.writeln("");
document.writeln("                    <div class=\'footer-center-left\'>");
document.writeln("                        <div class=\'left-font-top\'>工业互联网产业联盟版权所以有</div>");
document.writeln("");
document.writeln("                        <ul class=\'left-font\'>");
document.writeln("                            <li>");
document.writeln("                                <span>指导单位:</span>");
document.writeln("                                <span>xxxxxx</span>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                    <span>秘书处单位:</span>");
document.writeln("                                    <span>xxxxxx</span>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                    <span>电话:</span>");
document.writeln("                                    <span>xxxxxx</span>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                    <span>邮箱:</span>");
document.writeln("                                    <span>xxxxxx</span>");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                      ");
document.writeln("                         <div class=\'left-icon\'>");
document.writeln("                             <div class=\'left-icon-box\'>");
document.writeln("                                 <span></span>");
document.writeln("                                 <p>头条</p>");
document.writeln("                             </div>");
document.writeln("                             <div class=\'left-icon-box\'>");
document.writeln("                                <span></span>");
document.writeln("                                <p>微信</p>");
document.writeln("                             </div>");
document.writeln("                             <div class=\'left-icon-box\'>");
document.writeln("                                <span></span>");
document.writeln("                                <p>邮箱</p>");
document.writeln("                             </div>");
document.writeln("                         </div>");
document.writeln("");
document.writeln("                         <div>");
document.writeln("                             <p>友情链接: 工业和信息化部 | 中国信息通信院 | 美国工业互联网联盟 | 中国通信标准化协会</p>");
document.writeln("                         </div>");
document.writeln("                    </div>");
document.writeln("");
document.writeln("                    ");
document.writeln("                    <div class=\'footer-center-right\'>");
document.writeln("                            <div class=\'footer-center-right-right\'>联系我们</div>");
document.writeln("                            <ul class=\'right-font\'>");
document.writeln("                                <li>生态合作</li>");
document.writeln("                                <li>加入联盟</li>");
document.writeln("                                <li>联系方式</li>");
document.writeln("                           ");
document.writeln("                            </ul>");
document.writeln("                          ");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("");
document.writeln("            </div>");
document.writeln("    ");
document.writeln("</body>");
document.writeln("");
document.writeln("<script src=\'../jq/jq.js\'></script>");
document.writeln("<script src=\'../bootstrap/bootstrap-3.3.7-dist//js/bootstrap.min.js\'></script>");
document.writeln("<script>");
document.writeln("");
document.writeln(" ");
document.writeln("");
document.writeln("</script>");
document.writeln("</html>");