document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'zh-CN\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'ie=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\'>");
document.writeln("");
document.writeln("");
document.writeln("    <link rel=\'stylesheet\' href=\'../bootstrap/bootstrap-3.3.7-dist/css/bootstrap.min.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/main.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/head.css\'>");
document.writeln("");
document.writeln("    <title>Document</title>");
document.writeln("   ");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <nav class=\'navbar navbar-default\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("          <div class=\'navbar-header\'>");
document.writeln("            <button type=\'button\' class=\'navbar-toggle collapsed\' data-toggle=\'collapse\' data-target=\'#bs-example-navbar-collapse-1\' aria-expanded=\'false\'>");
document.writeln("              <span class=\'sr-only\'>Toggle navigation</span>");
document.writeln("              <span class=\'icon-bar\'></span>");
document.writeln("              <span class=\'icon-bar\'></span>");
document.writeln("              <span class=\'icon-bar\'></span>");
document.writeln("            </button>");
document.writeln("            <a class=\'navbar-brand\' href=\'#\'><img src=\'../images/logo.png\' alt=\'\' class=\'headimg\'></a>");
document.writeln("          </div>");
document.writeln("      ");
document.writeln("       ");
document.writeln("          <div class=\'collapse navbar-collapse\' id=\'bs-example-navbar-collapse-1\'>");
document.writeln("            <ul class=\'nav navbar-nav\'>");
document.writeln("              <li class=\'active\'><a href=\'#\'>首页 <span class=\'sr-only\'>(current)</span></a></li>");
document.writeln("              <li><a href=\'#\'>联盟介绍</a></li>");
document.writeln("              <li><a href=\'#\'>联盟动态</a></li>");
document.writeln("              <li><a href=\'#\'>在线课程</a></li>");
document.writeln("              <li><a href=\'#\'>供需平台</a></li>");
document.writeln("              <li><a href=\'#\'>成果发布</a></li>");
document.writeln("              <li><a href=\'#\'>线上展厅</a></li>");
document.writeln("              <li><a href=\'#\'>联系我们</a></li>");
document.writeln("             ");
document.writeln("            </ul>");
document.writeln("          ");
document.writeln("            ");
document.writeln("            <form class=\'navbar-form navbar-right\'>");
document.writeln("               ");
document.writeln("                <button type=\'submit\' class=\'btn btn-default\'>会员登入</button>");
document.writeln("              </form>");
document.writeln("           ");
document.writeln("            ");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </nav>");
document.writeln("");
document.writeln("  <!-- <div class=\'container\'>");
document.writeln("     <div class=\'row\'>");
document.writeln("       <div class=\'col-lg-2 col-md-2  col-sm-6  col-xs-6 \'>");
document.writeln("          <a  href=\'#\'><img src=\'../images/logo.png\' alt=\'\' class=\'headimg\'></a>");
document.writeln("       </div>");
document.writeln("       <div class=\'col-lg-8 col-md-8  col-sm-12  col-xs-12 dingji-top \'>");
document.writeln("           <ul>");
document.writeln("              <li class=\'active\'><a href=\'#\'>首页 <span class=\'sr-only\'>(current)</span></a></li>");
document.writeln("              <li><a href=\'#\'>联盟介绍</a></li>");
document.writeln("              <li><a href=\'#\'>联盟动态</a></li>");
document.writeln("              <li><a href=\'#\'>在线课程</a></li>");
document.writeln("              <li><a href=\'#\'>供需平台</a></li>");
document.writeln("              <li><a href=\'#\'>成果发布</a></li>");
document.writeln("              <li><a href=\'#\'>线上展厅</a></li>");
document.writeln("              <li><a href=\'#\'>联系我们</a></li>");
document.writeln("           </ul>");
document.writeln("       </div>");
document.writeln("       <div class=\'col-lg-2 col-md-2  col-sm-6  col-xs-6 \'>");
document.writeln("          <button type=\'submit\' class=\'btn btn-default\'>会员登入</button>");
document.writeln("       </div>");
document.writeln("     </div>");
document.writeln("  </div> -->");
document.writeln("  ");
document.writeln("</body>");
document.writeln("");
document.writeln("<script src=\'../jq/jq.js\'></script>");
document.writeln("<script src=\'../bootstrap/bootstrap-3.3.7-dist//js/bootstrap.min.js\'></script>");
document.writeln("<script>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</script>");
document.writeln("</html>");